---
swagger: '2.0'
info:
    version: "0.0.1"
    title: PRMS Fire Scenarios
    description: |
        This API will serve as the backbone of PRMS fire scenario modeling. 
        The immediate use will be in a web browser and Unity apps. However this
        will enable the PRMS tool to be used in any client that can make HTTP
        calls.

#host: virtualwatershed.org
host: "localhost:5000"
basePath: /api

schemes:
    - http
    - https
consumes:
    - application/json
produces:
    - application/json

tags:
- name: scenarios


paths:

    #############
    # Scenarios #
    #############
    /base-veg-map:
        get:
            summary: get the base map used to generate initial view of landscape
            tags:
                - scenarios
            operationId: getBaseVegetationMap

            responses:
                200:
                    description: "successful operation"
                    schema:
                        $ref: "#/definitions/VegMap"

    /scenarios:
        get:
            summary: list all scenarios
            tags:
                - scenarios
            operationId: listCompletedScenarios

            responses:
                200:
                    description: "successful operation"
                    schema:
                        type: object
                        schema:
                            $ref: "#/definitions/Scenarios"

        post:
            summary: request a new scenario
            tags: 
                - scenarios
            operationId: runNewScenario

            parameters:
                - name: vegetation_updates
                  type: object
                  description: list of 
                  in: body
                  schema:
                      $ref: "#/definitions/VegetationUpdates"
                - name: name
                  type: string
                  description: descriptive name for the scenario
                  in: body
                      

            responses:
                200:
                    description: "successful operation"
                    schema:
                        $ref: "#/definitions/Scenario" 

    /scenarios/{scenarioId}:
        get:
            summary: lookup a scenario by its id
            tags:
                - scenarios
            operationId: getScenario

            parameters:
                - name: scenarioId
                  in: path
                  required: true
                  type: string


            responses:
                200:
                    description: "successful operation"
                    schema:
                        $ref: "#/definitions/Scenario" 

        delete:
            summary: remove a scenario by its id
            tags:
                - scenarios
            operationId: deleteScenario

            parameters:
                - name: scenarioId
                  in: path
                  required: true
                  type: string


            responses:
                200:
                    description: "successful operation"


###################
#   DEFINITIONS   #
###################
# 
#
definitions:

    Scenario:

        type: object
        properties:
            name:
                type: string
                description: scenario name, to be used as description as well
            id:
                type: string
                description: server-generated id for scenario
            time_received:
                type: string
                format: date-time
                description: auto-generated by server when scenario request received
            time_finished:
                type: string
                format: date-time
                description: auto-generated by server when scenario model has finished
            veg_map_by_hru:
                type: object
                description: object with hru indices in array by vegetation code (0-4)
                schema:
                    type:
                        $ref: "#/definitions/VegMapByHRU"
            inputs:
                type: object
                description: download links to control, data, and parameter files for scenario
                schema:
                    type:
                        $ref: "#/definitions/Input"
            outputs:
                type: object
                description: download links to PRMS output files for scenario
                schema:
                    type:
                        $ref: "#/definitions/Output"
            hydrograph:
                type: object
                description:
                    keys of this object are datetimes, values are streamflow rates
                    in cubic feet per second (cfs)

    Input:
        type: object
        properties:
            control:
                type: string
                description: download link to control file used in scenario
            parameter:
                type: string
                description: download link to parameter file used in scenario
            data:
                type: string
                description: download link to data file used in scenario

    Output:
        type: object
        description: download links to PRMS output files
        properties:
            file1: string
            description: yo

    VegMap:
        type: object
        description: vegetation map presented to client that can be modified
        properties:
            projection_information:
                type: object
                schema:
                    $ref: '#/definitions/VegMapInfo'
            vegetation_map:
                type: object
                schema:
                    $ref: '#/definitions/VegMapByHRU'

    VegMapProjInfo:
        properties:
            cellsize(m): 
                type: float
            ncol:
                type: integer
            nrow:
                type: integer
            xllcorner:
                type: float
            xurcorner:
                type: float
            yllcorner:
                type: float
            yurcorner:
                type: float

    VegMapByHRU:
        properties:
            bare_ground:
                type: object
                schema:
                    $ref: '#/definitions/CellsByVegType'
            grasses:
                type: object
                schema:
                    $ref: '#/definitions/CellsByVegType'
            shrubs:
                type: object
                schema:
                    $ref: '#/definitions/CellsByVegType'
            trees:
                type: object
                schema:
                    $ref: '#/definitions/CellsByVegType'
            conifers:
                type: object
                schema:
                    $ref: '#/definitions/CellsByVegType'
                
    CellsByVegType:
        properties:
            HRU_number:
                type: array
                items:
                    type: integer

    VegetationUpdate:
        properties:
            cov_type_code:
                type: integer
                description: PRMS vegetation code (0-4)
            HRU_number:
                type: array
                items:
                    type: integer

    VegetationUpdates:
        properties:
            vegetation_updates:
                type: array
                items:
                    type: object
                    schema:
                        $ref: '#/definitions/VegetationUpdate'

    Scenarios:
        properties:
            scenarios:
                type: array
                items:
                    type: object
                    schema:
                        $ref: '#/definitions/Scenario'


